# Generated by Django 4.1 on 2024-10-24 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_funcionario_cargo_funcionario_data_admissao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(default='Funcionario', max_length=50),
        ),
    ]
